"""Event - Project change from one2one to many2one

Revision ID: 229ba755a8e6
Revises: d67bb3e15efd
Create Date: 2023-06-17 15:33:16.554481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229ba755a8e6'
down_revision = 'd67bb3e15efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'projects', ['project_id'], ['id'])
    op.drop_constraint('projects_event_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_event_id_fkey', 'projects', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'project_id')
    # ### end Alembic commands ###
