"""User timestamped

Revision ID: 438a2d788e31
Revises: cf0c775dd340
Create Date: 2023-06-17 09:52:36.793765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438a2d788e31'
down_revision = 'cf0c775dd340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
