"""new column User.account_type

Revision ID: 76858a86dce0
Revises: 438a2d788e31
Create Date: 2023-06-17 09:56:26.281111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76858a86dce0'
down_revision = '438a2d788e31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
