"""relationships Post >- Project

Revision ID: d67bb3e15efd
Revises: ef37162c18ac
Create Date: 2023-06-17 15:18:32.734993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67bb3e15efd'
down_revision = 'ef37162c18ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'project_id')
    # ### end Alembic commands ###
